language: go

go:
    - tip

install:
    - go get code.google.com/p/gcfg
    - go get gopkg.in/simversity/gottp.v2
    - go get github.com/HouzuoGuo/tiedot

script:
    - go build -v ./...

notifications:
  slack: siminars:st82ura5uv0xQ52hTmHCqiNs
